services:
  app:
    build: .
    ports:
      - 8080:8080
    networks:
      - netapp
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_PASSWORD: faisalg5
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: faisalg5
    volumes:
      - data_postgres:/var/lib/postgresql/data
    networks:
      - netapp
  redis:
    image: redis
    volumes:
      - data_redis:/data
    networks:
      - netapp
volumes:
  data_postgres:
  data_redis:
networks:
  netapp: