services:
    app:
        build: .
        ports:
            - 8080:8080
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=faisalg5
        ports:
            - 5433:5432
    redis:
        image: redis
        ports:
            - 6380:6379