services:
  app:
    image: ghcr.io/vsalcode/fgo24-be-crud:latest
    ports:
      - 8080:8080
    networks:
      - netapp
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: faisalg5
    volumes:
      - data_postgres:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - netapp
  redis:
    image: redis
    volumes:
      - data_redis:/data
    networks:
      - netapp
volumes:
  data_postgres:
  data_redis:
networks:
  netapp: