services:
    app:
        build: .
        ports:
            - 8080:8080
    postgres:
        image: postgres
        environment:
            - POSTGRES_PASSWORD=faisalg5
    redis:
        image: redis