services:
  app:
    image: ghcr.io/VsalCode/be-crud:latest
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=app_user
      - DB_PASSWORD=faisalg5
      - DB_NAME=app_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: faisalg5
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  redis_data:
