name: push backend image to ghcr
run-name: release image to ghcr
on: [push]
jobs:
  push-image-to-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Build and publish Docker image
        uses: macbre/push-to-ghcr@master
        with:
          image_name: vsalcode/fgo24-be-crud
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy-to-vps:
  runs-on: ubuntu-latest
  steps:
    - name: Connect & Deploy to VPS
      uses: appleboy/ssh-action@v0.1.12
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "Checking current directory..."
          pwd
          ls -l  
          echo "Pulling latest image from GHCR..."
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u VsalCode --password-stdin
          docker pull ghcr.io/vsalcode/fgo24-be-crud:latest
          echo "Stopping existing container..."
          docker compose down || true
          echo "Navigating to the project directory..."
          cd /path/to/project/directory || exit 1  
          ls -l  
          echo "Starting Docker Compose..."
          docker compose up -d
