name: Push backend image to GHCR
run-name: Release Image GHCR
on:
  push:
    branches:
      - main
jobs:
  push-image-toghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/vsalcode/fgo24-be-crud:latest

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: 9401
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/faisal/deploy
            docker pull ghcr.io/vsalcode/fgo24-be-crud:latest
            docker compose down || true
            docker compose up -d